### ISSUE TITLE
Pressing  any part of the progress bar would cause the audio to go back to restart

### ISSUE THREAD

**Issue by paullam328** [lhz516/react-h5-audio-player#32] opened 2020-03-26 04:04 UTC
I tried pressing/dragging any part of the progress bar to skip through the audio, but every time I do that, the audio would just skip back to the beginning, which makes it impossible to navigate to the middle/later part of the audio...

**Comment by lhz516** [comment] 2020-03-26 04:38
I'm not able to reproduce that. Could you provide some environment specs?

Package version:
React version:
Browser and its version:
OS and its version:

**Comment by paullam328** [comment] 2020-03-26 07:33
Package version: 3.0.1
React version: 16.9.0
Browser and its version: Chrome Version 80.0.3987.149 
OS and its version: Windows 10 Version 1909

**Comment by lhz516** [comment] 2020-03-26 23:56
Sorry but I'm still not able to reproduce the bug you described.

Do you have any issues interacting with the demo ones? https://static.hanzluo.com/react-h5-audio-player-storybook/index.html?path=/docs/layouts--default-story

**Comment by paullam328** [comment] 2020-03-27 00:07
Thanks for following up.  The demo ones work perfectly, and I also downloaded the same audio from that page to test it out, in which the bug still persists with the mp3 audio file downloaded from your demo webpage

**Comment by lhz516** [comment] 2020-03-27 01:55
Hmm, the demo ones are the latest version.

It seems a tricky issue. My guess is some event handlers in your application causes a side effect.

This audio player component uses some `window.addEventListener` to handle mouse move and mouse up, and removes the handlers right after the user releases the mouse.

Could you investigate your application to see if there are any event handlers (especially window event handler) which can possibly cause any UX issues?

**Comment by Shion093** [comment] 2020-04-01 16:00
Having the same issue, it goes back to zero

**Comment by lhz516** [comment] 2020-04-02 03:35
@paullam328 @Shion093 

I hope I can help, but I really couldn't reproduce this issue.

I may need you to do some debug for me.

Could you check if it goes to this branch which sets currentTime to 0？
https://github.com/lhz516/react-h5-audio-player/blob/1fb78e4af070c3006e075367f589f7c19883f733/src/ProgressBar.tsx#L51

If not, what are the values of `this.props.audio.duration`, `relativePos` and `maxRelativePos`?
https://github.com/lhz516/react-h5-audio-player/blob/1fb78e4af070c3006e075367f589f7c19883f733/src/ProgressBar.tsx#L63

**Comment by Shion093** [comment] 2020-04-02 03:42
Hi @lhz516 , I'm sorry the error was on my end, as I was suing Azure Blobs to get the .mp3 file, the default service version was 2009, so it didn't include Partial Content, after updating the service to last version it works just fine. 

But now I'm having  this error
` Cannot read property 'togglePlay' of undefined`

Error line 
` if (_this.state.audioLists.length >= 1) {
          _this.lyric.togglePlay();`

After I hit reload button it works and starts playing.

Sorry again for hijacking this thread.

**Comment by lhz516** [comment] 2020-04-02 04:00
@Shion093 Thanks for the info.

@paullam328 Could you check if it is also your case?

**Comment by JeffreyCA** [comment] 2020-04-25 19:25
I experienced this issue when running a Django server in development mode. Your webserver needs to support bytes range requests for you to be able to skip to different parts in the audio.

**Comment by lhz516** [comment] 2020-04-28 22:50
Yea, looks like a server issue. Closing it

**Closed by lhz516** 2020-04-28 22:50 UTC
Labels: bug

**Comment by paullam328** [comment] 2020-07-21 00:06
Seems like the most direct solution to the issue isn't addressed in here, in which I have just discovered the solution to such.

Apparently for any audio/video file, Chrome has that weird issue.  For every file with a URL of different parameter, when the consumer would like to drag/click the progress bar to listen to another part of an audio/watch next part of video, the progress bar jumps back to the beginning.

This seems to be the fact that Google needs a Content-Range configuration and "Accept-Ranges: bytes" in the header being sent from the back-end in the audio/video file storage API call, for the play time to be editable dynamically. (which seems to be the most direct, and yet tedious to test solution, see: https://github.com/sampotts/plyr/issues/1101, https://github.com/sampotts/plyr/issues/1444, https://stackoverflow.com/questions/11340276/make-mp3-seekable-php).

Therefore, I've figured out a workaround.  A blob file doesn't contain any url parameters, so all I have to do is to convert the audio/video file to a blob, then generate a local url from the blob, and then generate an AudioPlayer/VideoPlayer from the blob's url, now the progress bar works normally, and can be dragged as desired.

For anyone who's struggling with such issue, here's the solution:
`class MediaContent extends React.Component {

    constructor(props) {
        super(props);
        this.player = React.createRef();
        this.state = {
            //just for audio/video, Chrome has that weird issue where URL with parameters --> progress bar jumps back to 0 on drag:
            audioBlobURL: "",
            isAudioBlobCreated: false
        }
    }

    async componentDidMount() {
        if (this.props.contentType == HubConstant.MEDIA_CONTENT_AUDIO || this.props.contentType == HubConstant.MEDIA_CONTENT_VIDEO) {
            let blob = await fetch(this.props.mediaUrl).then(r => r.blob());
            this.setState({audioBlobURL: URL.createObjectURL(blob)}, () => this.setState({isAudioBlobCreated: true}));
        } else {
            this.setState({isAudioBlobCreated: true});
        }
    }

 render() {
        if (this.props.mediaUrl && this.state.isAudioBlobCreated) {
                                        <AudioPlayer src={this.state.audioBlobURL} ref={this.player} volume={0.6} autoPlay={false} autoPlayAfterSrcChange={false}></AudioPlayer>
                    );
  }
}`

**Comment by dogakorkmaz35** [comment] 2025-11-27 22:14
@paullam328 saving it!!

**Comment by jason-ezenwa** [comment] 2025-12-08 20:13
> Seems like the most direct and easiest solution to the issue isn't addressed in here, for which I have just discovered:
> 
> Apparently for any audio/video file, Chrome has that weird issue. For every file with a URL of different parameter, when the consumer would like to drag/click the progress bar to listen to another part of an audio/watch next part of video, the progress bar jumps back to the beginning.
> 
> This seems to be the fact that Google needs a Content-Range configuration and "Accept-Ranges: bytes" in the header being sent from the back-end in the audio/video file storage API call, for the play time to be editable dynamically. (which seems to be the most direct, and yet tedious to test solution, see: [sampotts/plyr#1101](https://github.com/sampotts/plyr/issues/1101), [sampotts/plyr#1444](https://github.com/sampotts/plyr/issues/1444), https://stackoverflow.com/questions/11340276/make-mp3-seekable-php).
> 
> Therefore, I've figured out a workaround. A blob url doesn't contain any parameter, which means creating a blob is the way to go!
> 
> All I have to do is to convert the audio/video file to a blob, then generate a local url from the blob, and then generate an AudioPlayer/VideoPlayer from the blob's url, now the progress bar works normally, and can be dragged as desired.
> 
> For anyone who's struggling with such issue, here's the solution:
> 
> ```
> class MediaContent extends React.Component {
>    //i.e., this.props.mediaUrl is the one encountering such issue
>     constructor(props) {
>         super(props);
>         this.player = React.createRef();
>         this.state = {
>             audioBlobURL: "",
>             isAudioBlobCreated: false
>         }
>     }
> 
>     async componentDidMount() {
>             let blob = await fetch(this.props.mediaUrl).then(r => r.blob());
>             this.setState({audioBlobURL: URL.createObjectURL(blob)}, () => this.setState({isAudioBlobCreated: true}));
>     }
> 
>  render() {
>     return (
>        (!!this.props.mediaUrl && this.state.isAudioBlobCreated) ?
>           <AudioPlayer src={this.state.audioBlobURL} ref={this.player}></AudioPlayer>
>            : <> </>
>    )
> }
> ```

found your response while working on a custom audio player and experiencing this (in my case progress bar worked fine locally but always restarted in production). thank you!!
