### ISSUE TITLE
got audio is undefined when componentWillUnmount

### ISSUE THREAD

**Issue by JackHuang16** [lhz516/react-h5-audio-player#28] opened 2020-03-02 16:22 UTC
hi 
I got audio variation is undefined when componentWillUnmount.

it happened in CurrentTime.js, Duration.js, ProgressBar.js, and VolumeBar.js when componentWillUnmount

and I change it to this, everything goes fine.

CurrentTime.js
`
_proto.componentWillUnmount = function componentWillUnmount() {
    var audio = this.props.audio;

    if( audio && this.hasAddedAudioEventListener ) {
      audio.removeEventListener('timeupdate', this.handleAudioCurrentTimeChange);
      audio.removeEventListener('loadedmetadata', this.handleAudioCurrentTimeChange);
      this.hasAddedAudioEventListener = false;
    }
  };
`

Duration.js
`
_proto.componentWillUnmount = function componentWillUnmount() {
    var audio = this.props.audio;

    if (audio && this.hasAddedAudioEventListener) {
      audio.removeEventListener('durationchange', this.handleAudioDurationChange);
      this.hasAddedAudioEventListener = false;
    }
  };
`

VolumeBar.js
`
_proto.componentWillUnmount = function componentWillUnmount() {
    var audio = this.props.audio;

    if (audio && this.hasAddedAudioEventListener) {
      audio.removeEventListener('volumechange', this.handleAudioVolumeChange);
      this.hasAddedAudioEventListener = false;
    }
    clearTimeout(this.volumeAnimationTimer);
  };
`

ProgressBar.js
`
_proto.componentWillUnmount = function componentWillUnmount() {
    var audio = this.props.audio;

    if (audio && this.hasAddedAudioEventListener) {
      audio.removeEventListener('timeupdate', this.handleAudioTimeUpdate);
      audio.removeEventListener('progress', this.handleAudioDownloadProgressUpdate);
      this.hasAddedAudioEventListener = false;
    }

    clearTimeout(this.downloadProgressAnimationTimer);
  };
`

please check it

Thanks a lot : )

<img width="534" alt="Screen Shot 2020-03-03 at 12 10 49 AM" src="https://user-images.githubusercontent.com/8913003/75695192-aa703280-5ce4-11ea-9244-4d2721b02e85.png">
<img width="820" alt="Screen Shot 2020-03-03 at 12 11 05 AM" src="https://user-images.githubusercontent.com/8913003/75695200-ae03b980-5ce4-11ea-95dc-c44d13ced6de.png">
<img width="589" alt="Screen Shot 2020-03-03 at 12 12 30 AM" src="https://user-images.githubusercontent.com/8913003/75695204-afcd7d00-5ce4-11ea-8570-98256d2ce40d.png">

**Comment by lhz516** [comment] 2020-03-02 16:28
Thanks for reporting. Which package version is it? How do you reproduce this exactly?

**Comment by JackHuang16** [comment] 2020-03-03 02:08
My version is ^2.4.1.
I have a search bar for users to input, then call the API to present the result with react-h5-audio-player.
The first time is no problem, but when the user search again, it will crash by that.

Thanks

**Comment by lhz516** [comment] 2020-03-03 04:29
The fix is easy but I can't reproduce that and don't know the root cause.

I just published `2.4.2-beta.0` and `2.4.2-beta.1` using two different ways.

Could you check if both work for you or only the second one works for you? After that I'll publish the formal `2.4.2`

**Comment by JackHuang16** [comment] 2020-03-03 12:08
only  2.4.2-beta.1 worked fine in my scenario
2.4.2-beta.0 still got the same error
thanks a lot : )

**Comment by lhz516** [comment] 2020-03-04 04:45
Thanks for testing. Published `2.4.2`. Closing

**Closed by lhz516** 2020-03-04 04:45 UTC
Labels: bug
