### ISSUE TITLE
Play button need click twice after first play complete in IE11

### ISSUE THREAD

**Issue by wzhonggo** [lhz516/react-h5-audio-player#104] opened 2021-03-21 04:02 UTC
**Describe the bug**

First time click play and play music complete.  Music not play when second time click play button.  
The play button not change and has outline. see screenshot  ![image](https://user-images.githubusercontent.com/2763532/111893301-c1dba400-8a3c-11eb-87d4-c7b0b7176a35.png).  Music is play when third time click play button.  It only can reproduce on IE11.  

**Environment**

Package version: 3.6.1 or 3.6.2
React version: 17.0.1
Browser and its version: IE 19041.804
OS and its version: Windows 10 Build 19041.804

**Comment by lhz516** [comment] 2021-03-26 08:19
I figured out the cause. When audio ends:
In Chome/Edge/FF, it triggers both `pause` and `ended` event.
In IE, it only trigger `ended` event.

I'll give a fix on weekends

**Comment by lhz516** [comment] 2021-04-04 08:04
Fixed and released [v3.7.0](https://github.com/lhz516/react-h5-audio-player/releases/tag/v3.7.0)

Closing the issue. Feel free to continue the discussion if needed.

**Closed by lhz516** 2021-04-04 08:04 UTC
Labels: bug

**Comment by nb312** [comment] 2022-02-07 08:53
I use the lastest version, but it also has the same problem, it should be click twice to play.
