### ISSUE TITLE
Console Error when moving audio bar

### ISSUE THREAD

**Issue by lloydrhodes87** [lhz516/react-h5-audio-player#64] opened 2020-08-23 09:54 UTC
**Describe the bug**

I get the following error in the console when scrolling the audio bar. 

[Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. 

I have changed quite a bit of css so hopefully that is not having anything to do with it but thought i would raise it. 

**Environment**

Package version: ^3.3.2
React version: ^16.12.0
Browser and its version: Chrome 84.0.4147.125
OS and its version:

**Comment by lhz516** [comment] 2020-08-24 08:09
Hi, it's not reproducible on my side. Maybe it's related to the `props` you passed into the player?

Could you fork this codepen https://codepen.io/lhz516/pen/dyGpmgP and make a reproducible example ?
(Fork button is on the page footer)

**Comment by lhz516** [comment] 2020-09-05 04:44
Closing. Feel free to reopen if it's you can provide more details and a reproducible example.

**Closed by lhz516** 2020-09-05 04:44 UTC
Labels: bug, invalid

**Comment by AlanFnz** [comment] 2020-11-22 15:18
Having the same issue here:

VolumeBar.js:109 [Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/5093566007214080

**Comment by lhz516** [comment] 2020-11-22 19:37
@AlanFnz Thanks for the info! However, I'm not able to reproduce it. I'm glad to fix it if you can fork this [codepen](https://codepen.io/lhz516/pen/dyGpmgP) and make a reproducible example
