### ISSUE TITLE
Audio not autoplaying upon first src change

### ISSUE THREAD

**Issue by AshleighParsons** [lhz516/react-h5-audio-player#57] opened 2020-07-23 06:51 UTC
I'm using useContext to update the media player from multiple pages within my app. 
This works as it should, however when the app starts up for the first time, the src is set to an empty string. Once play is clicked, the information is updated on the media player (ie the image, name and audio time is visible) but the media is paused. 
If I change to a different audio src after this, the media plays (as it should on src change).

Just wanting to find out if there is a way to have the media play on src change, when the previous src is either an empty string or undefined?

**Comment by bruceontheloose** [comment] 2020-07-23 18:15
Hi, @AshleighParsons,

I ran into this too. My hack-ish solution, at least for the time being, was to set the default audio source to a very short, blank MP3 instead of an empty string. I used the 250-millsecond one from https://github.com/anars/blank-audio. 

Even with that, and as you may know, Safari (macOS and iOS) won't autoplay when you switch the player's source to a legitimate src. So you'll have to both switch the src and fire the player's play method. Something like this: `YOUR_REFERENCE_TO_THE_PLAYER_GOES_HERE.current.audio.current.play()`. At least that's what I did.

I'd be interested in a more elegant approach, though, so if you get it working, it'd be great if you could share it here. 

I also have a case that doesn't work: you click/tap your Play button that is outside the player, pause via the button on the player itself, and then click/tap the Play button (outside the player again) for the same audio source. In that case, playback doesn't resume. I spent a little time looking into it before moving on to other tasks.

Thanks,

Bruce

**Comment by lhz516** [comment] 2020-07-24 17:40
I tried it in codepen https://codepen.io/lhz516/pen/Rwrdqov

The initial src is an empty string. When you click on "Set new src", it auto plays

If that's not your case, could you fork the above codepen and make a reproducable example?

**Comment by AshleighParsons** [comment] 2020-08-02 19:26
Hi @bruceontheloose 
Thanks for the response, this did work for me, but I was also looking for a less convoluted solution! I will let you know if I happen upon one.

And thank you @lhz516 for the response as well. This does work as expected when autoplay is on, however I am storing the audio source locally so that it is available upon page reload. This issue with this is that I do not want the media player to automatically play each time the page refreshes.
So, ideally, I'd like autoplay to be false, but autoPlayAfterSrcChange to be true!

**Comment by lhz516** [comment] 2020-08-02 21:15
@AshleighParsons 
When `autoPlayAfterSrcChange` is `true`, no matter `autoPlay` is `true` or `false`, the audio should auto play after the src changes. However, it currently only happens when you switch from a valid url to another valid url.

If you change src from an empty string to a valid url, even if `autoPlayAfterSrcChange` is `true`, the audio won't auto play after src changes. That's because the logic happens in the audio's `abort` event handler, and `abort` event only triggers when the src is changed from a valid url to another valid url.

I would consider this a bug. With `autoPlayAfterSrcChange`  turned on, the correct behavior should be no matter the current audio url is valid or not, it always auto play after src changes 

I'm putting this on the roadmap, and fix it in the next release.

**Comment by AshleighParsons** [comment] 2020-08-03 07:02
@lhz516 Thanks for the explanation

**Comment by lhz516** [comment] 2020-08-12 05:23
Released 3.3.0 https://github.com/lhz516/react-h5-audio-player/releases/tag/v3.3.0

Closing the issue. Feel free to continue the discussion if needed.

**Closed by lhz516** 2020-08-12 05:23 UTC
Labels: bug
